package org.javabase.apps.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart")
public class Cart implements java.io.Serializable {

	private static final long serialVersionUID = -3773700977852899109L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cart_id", unique = true, nullable = false)
	private Integer cartId;
	
	@Column(name = "user_id", nullable = false)
	private int userId;
	
	@Column(name = "product_id", nullable = false)
	private int productId;
	
	@Column(name = "product_item", nullable = false)
	private int productItem;
	
	@Column(name = "total_price", nullable = false)
	private int totalPrice;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	private Date createDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_date", nullable = false, length = 19)
	private Date expireDate;
	
	@Column(name = "is_expired", nullable = false)
	private byte isExpired;

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getProductItem() {
		return this.productItem;
	}

	public void setProductItem(int productItem) {
		this.productItem = productItem;
	}

	public int getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	public byte getIsExpired() {
		return this.isExpired;
	}

	public void setIsExpired(byte isExpired) {
		this.isExpired = isExpired;
	}

}


