package org.javabase.apps.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase")
public class Purchase implements java.io.Serializable {

	private static final long serialVersionUID = 2489126067268432501L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "purchase_id", unique = true, nullable = false)
	private Integer purchaseId;
	
	@Column(name = "user_id", nullable = false)
	private int userId;
	
	@Column(name = "total_products", nullable = false)
	private int totalProducts;
	
	@Column(name = "total_item", nullable = false)
	private int totalItem;
	
	@Column(name = "total_price", nullable = false)
	private int totalPrice;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_date", nullable = false, length = 19)
	private Date purchaseDate;

	
	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	
	public int getTotalProducts() {
		return this.totalProducts;
	}

	public void setTotalProducts(int totalProducts) {
		this.totalProducts = totalProducts;
	}

	
	public int getTotalItem() {
		return this.totalItem;
	}

	public void setTotalItem(int totalItem) {
		this.totalItem = totalItem;
	}

	
	public int getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}
	
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

}


